### ISSUE TITLE
config.cache_store hash syntax is not being applied

### ISSUE THREAD

**Issue by nasheed-moiz** [redis-store/redis-rails#25] opened 2015-08-03 19:37 UTC
I am trying to configure Rails cache to use redis-store, and use host, port etc from a yml. To test I changed the redis port to 6370, in order to find out if it works.
```ruby
    rails_root = ENV['RAILS_ROOT'] || File.dirname(__FILE__) + '/..'
    rails_env = ENV['RAILS_ENV'] || 'development'

    # load contents of YAML
    redis_config = YAML.load(ERB.new(File.read(rails_root + '/config/redis.yml')).result)


    config.cache_store = :redis_store, { host: redis_config[rails_env]['url'],
                                         port: redis_config[rails_env]['port'], # set in yml to 6370
                                         password: redis_config[rails_env]['password'],
                                         namespace: 'my_app' }
```
Above snippet is on my application.rb
My local redis server runs on localhost:6370.

Upon starting a rails console, and running Rails.cache, this is what I get.
```#<ActiveSupport::Cache::RedisStore:0x007fa051130490 @options={:host=>"localhost", :port=>6370, :password=>nil, :namespace=>"my_app"}, @data=#<Redis client v3.2.1 for redis://127.0.0.1:6379/0>>```
The values in the options hash are correct, however, the values in @data object are incorrect, and I cannot change them for the life of me.
With these settings the cache doesnt work. It only works when I change above port values to 6379.

**Comment by nasheed-moiz** [comment] 2015-08-03 22:32
Update - using the url format with password, host, port, db, namespace etc interpolated, it worked. Hash format still wont work

**Comment by radar** [comment] 2015-08-04 21:28
If the hash format still won't work then I would consider that a bug and this issue should remain open. I'm gathering you "hash format" like this example from the README?

```ruby
config.cache_store = :redis_store, { :host => "localhost",
                                     :port => 6379,
                                     :db => 0,
                                     :password => "mysecret",
                                     :namespace => "cache",
                                     :expires_in => 90.minutes }
```

**Comment by jimbocortes** [comment] 2015-08-14 17:54
@nasheed-moiz  can you provide a sample using the url format? Just want to make sure.

**Comment by nasheed-moiz** [comment] 2015-08-14 18:00
config.cache_store = :redis_store, 'redis://localhost:6370/my_namespace', { expires_in: 24.hours }
This worked for me, with the custom port number for redis. With the hash format, it would always try to look for redis on the default port 6379

**Comment by jimbocortes** [comment] 2015-08-14 18:36
Thanks. url format works :+1:

**Comment by eggie5** [comment] 2015-08-20 17:36
I can confirm that this syntax works as expected: 

```
config.cache_store = :redis_store,  ENV.fetch('REDIS_CONNECTION_STRING'), { namespace: "mainframe:cache", expires_in: 90.minutes }
```

````
Rails.cache
=> #<ActiveSupport::Cache::RedisStore:0x007f8dd2161540 @data=#<Redis client v3.2.1 for redis://pub-redis-19351.us-east-1-3.6.ec2.redislabs.com:19351/0>, @options={:namespace=>"mainframe:cache", :expires_in=>5400 seconds}>
```

However, if you include `:db` in the hash, it will add localhost to the redis servers listed in the `Rails.cache` list. Seems like a parsing issue in the library.

**Comment by tubbo** [comment] 2016-02-02 16:53
Hey this syntax seems to work as expected since no one else is having this problem, so I'm gonna close the issue. Let me know if it's still happening for you...

**Comment by UnquietCode** [comment] 2016-02-02 17:31
I would just also add that the URL syntax worked for me while the hash syntax still does not work. Thanks.

**Comment by sagarey** [comment] 2016-02-24 09:13
+1, hash format doesn't work, but URL worked well.

**Comment by tubbo** [comment] 2016-05-31 18:49
@UnquietCode @sagarey I can't reproduce this at all. Please paste here the code you're using and the error you're getting.

**Comment by sagarey** [comment] 2016-06-03 07:03
@tubbo , I just follow the usage, use hash syntax options:
```ruby
# config/application.rb
config.cache_store = :redis_store, { host: "localhost",
                                     port: 6379,
                                     db: 1,
                                     namespace: "cache" }
```

there already a ```Issue.androids``` cache in db 1, but ``` Rails.cache.read('Issue.androids') ``` return nil, then I create a new cache, but it write to db 0, option db seem not work.
![rails cache hash cache](https://cloud.githubusercontent.com/assets/5120456/15770719/65566ee0-2998-11e6-92d5-ca06597a32d9.PNG)

type ``` Rails.cache  ``` in rails console, get this:
![rails cache hash](https://cloud.githubusercontent.com/assets/5120456/15770570/56e6f72c-2997-11e6-87d6-6ae86eed10e9.PNG)


then I try use URL as follow:
```ruby
config.cache_store = :redis_store, 'redis://localhost:6379/1/cache' 
```

it worked well:
![rails cache url](https://cloud.githubusercontent.com/assets/5120456/15770863/40bbeece-2999-11e6-98c3-0f56a9eda5ae.PNG)

**Comment by Petercopter** [comment] 2016-06-15 22:15
I'm having the same problem with the hash syntax. It's working for cache, but not for sessions.

**Comment by Petercopter** [comment] 2016-06-15 23:58
OK I was finally able to get it working with the hash syntax. Does anyone know why the cache config has the equal sign, and session does not? That tripped me up, I was craving consistency....

Here's what seems to be working, at the moment...
```
config.cache_store = :redis_store, { host: ENV['REDISTOGO_URL'], db: 0 }
# please note the lack of eql sign here!!!!!
config.session_store :redis_store, { host: ENV['REDISTOGO_URL'], db: 1, expires: 1.day }
```

**Comment by tubbo** [comment] 2016-06-16 14:06
That is, unfortunately, how Rails dictates these things should be
configured. I don't believe we have much of a say in it. A lot of other
gems, and especially cache backends, are configured this way so I'm not
too worried about it.

On 06/15, Peter Krutz wrote:
> OK I was finally able to get it working with the hash syntax. Does anyone know why the cache config has the equal sign, and session does not? That tripped me up, I was craving consistency....
> 
> Here's what seems to be working, at the moment...
> ```
> config.cache_store = :redis_store, { host: ENV['REDISTOGO_URL'], db: 0 }
> # please note the lack of eql sign here!!!!!
> config.session_store :redis_store, { host: ENV['REDISTOGO_URL'], db: 1, expires: 1.day }
> ```
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/redis-store/redis-rails/issues/25#issuecomment-226353921

-- 
- T

**Closed** 2016-06-27 18:20 UTC
Labels: bug
