### ISSUE TITLE
Don't crash the application if redis is down

### ISSUE THREAD

**Issue by brauliobo** [redis-store/redis-rails#14] opened 2014-12-01 17:48 UTC
Acts like `:dalli_store` or `:memcache_store` that if the server is not available caching is disabled and the application doesn't crash without it.

This is pretty critical!

```
  Error connecting to Redis on 127.0.0.1:6379 (ECONNREFUSED)
  redis (3.1.0) lib/redis/client.rb:309:in `rescue in establish_connection'
```

**Comment by ethagnawl** [comment] 2015-03-06 18:53
+1 @Paxa and @brauliobo! 

Is there a possibility that this patch will make into into the gem, @radar?

**Comment by dsandber** [comment] 2015-03-09 02:07
+1 -- I've been getting "Redis::CannotConnectError" and "Redis::TimeoutError" errors.  Given that Redis is just caching views for me there's no reason the user should see a website crash!

**Comment by radar** [comment] 2015-03-09 05:08
Please submit a PR to fix this issue.

**Comment by RailsCod3rFuture** [comment] 2015-04-05 01:21
I'm getting this error when users attempt to complete registration with Devise. Has the gem been updated to support the changes that you've made?

**Comment by RailsCod3rFuture** [comment] 2015-04-05 01:46
Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Redis::TimeoutError)):
  redis (3.2.1) lib/redis/client.rb:331:in `rescue in establish_connection'
  redis (3.2.1) lib/redis/client.rb:317:in `establish_connection'
  redis (3.2.1) lib/redis/client.rb:94:in `block in connect'
  redis (3.2.1) lib/redis/client.rb:279:in `with_reconnect'
  redis (3.2.1) lib/redis/client.rb:93:in `connect'
  redis (3.2.1) lib/redis/client.rb:350:in `ensure_connected'
  redis (3.2.1) lib/redis/client.rb:207:in `block in process'
  redis (3.2.1) lib/redis/client.rb:292:in `logging'
  redis (3.2.1) lib/redis/client.rb:206:in `process'
  redis (3.2.1) lib/redis/client.rb:177:in `call_pipelined'
  redis (3.2.1) lib/redis/client.rb:149:in `block in call_pipeline'
  redis (3.2.1) lib/redis/client.rb:279:in `with_reconnect'
  redis (3.2.1) lib/redis/client.rb:147:in `call_pipeline'
  redis (3.2.1) lib/redis.rb:2182:in `block in multi'
  redis (3.2.1) lib/redis.rb:37:in `block in synchronize'
  C:/Ruby214/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  redis (3.2.1) lib/redis.rb:37:in `synchronize'
  redis (3.2.1) lib/redis.rb:2174:in `multi'
  sidekiq (3.3.3) lib/sidekiq/client.rb:179:in `block in raw_push'
  connection_pool (2.1.3) lib/connection_pool.rb:62:in `with'
  sidekiq (3.3.3) lib/sidekiq/client.rb:178:in `raw_push'
  sidekiq (3.3.3) lib/sidekiq/client.rb:68:in `push'
  sidekiq (3.3.3) lib/sidekiq/worker.rb:84:in `client_push'
  sidekiq (3.3.3) lib/sidekiq/worker.rb:40:in `perform_async'
  devise-async-stretch (0.0.6) lib/devise/async/stretch/backend/sidekiq.rb:11:in `enqueue_job'
  devise-async-stretch (0.0.6) lib/devise/async/stretch/worker.rb:7:in `enqueue'
  devise-async-stretch (0.0.6) lib/devise/async/stretch/model.rb:34:in `enqueue_stre

**Comment by radar** [comment] 2015-04-12 22:19
Start your Redis server.

**Comment by Paxa** [comment] 2015-04-12 23:18
@radar, how about timeout error?

**Comment by radar** [comment] 2015-04-12 23:29
@Paxa I don't see a timeout error.

**Comment by Paxa** [comment] 2015-04-13 00:25
I had that error in production. We have multiple rails servers and cluster of redis servers. We never stop redis and internal network working well, but connection and timeout errors still happen sometimes. Hopefully I'm using this gem only for cache not for sessions so it's ok to ignore error and keep going.

**Comment by ethagnawl** [comment] 2015-04-13 14:40
> I don't see a stacktrace that doesn't have to do with a Redis server not running.

Isn't this the scenario we've been discussing, which the provided monkey patches account for?

The Rails process shouldn't crash if a Redis server isn't available (a la dalli store and memcache store). As far as I can tell, this issue has not yet been resolved.

**Comment by radar** [comment] 2015-04-14 04:12
A patch to support this would be great. Perhaps something that checked on server initalization if the Redis server couldn't be reached and then printed something to stderr informing the user about it.

I don't like the monkeypatching fix.

**Comment by dsandber** [comment] 2015-04-14 05:07
@radar That wouldn't be sufficient since the redis server could be up at initialization but then fail later -- when it does it shouldn't cause an application exception when it's being used as a cache.

**Comment by radar** [comment] 2015-04-14 06:25
If you took down your MySQL server while your Rails server was running, would you expect it to no-op with a `Rails.logger` message? I would think not. Why do you expect `redis-rails` to do that?

**Comment by ethagnawl** [comment] 2015-04-14 08:13
I don't think the comparison is warranted.

MySQL is The Source of Truth, while Rails.cache is not. (I wouldn't think 
Redis' durability is relevant here.) Rails.cache reads _can_ miss and 
recalculate and writes _can_ no-op.

**Comment by dsandber** [comment] 2015-04-14 21:38
If we were proposing this to Redis, I would agree that it wouldn't make sense.  I was under the impression that redis-rails was for the purpose (and only for the purpose) of using Redis as a cache for Rails.  If redis-rails is more general than this than it would make sense to have a flag specifying whether it is being used as a cache, or a separate class, or to fork the project.

**Comment by radar** [comment] 2015-04-15 04:02
It's not just for caching. It can be used as the session store too. If Redis goes down, there goes your sessions. It should do the Ruby equivalent of Go's `panic`: raise an exception, show a stacktrace and quit the process.

**Comment by radar** [comment] 2015-04-15 04:15
I think that it's better to show an error when redis-rails cannot connect to Redis rather than no-op. If someone's wanting to test out their caching strategy and their caching layer is no-op'ing mysteriously, it can be difficult to debug. Having it fail the moment that it can't connect to Redis is a better idea in my opinion.

If you can show me a case of this causing an actual bug in this gem rather than it be caused by someone not starting Redis correctly (or at all), then I'd like to continue the discussion about fixing it.

Until then, I'm considering this not a bug but a Problem Existing Between Keyboard and Chair.

**Comment by dsandber** [comment] 2015-04-15 04:19
I experienced this on my production site when intermittent networking issues occurred (or possibly when Amazon/Heroku did maintenance).

Because I was using redis-rails to cache fragments and the like, if redis-rails had returned null my users would've been able to continue using the website without noticing any problem.  Instead they were seeing the website exception page.  This is clearly the wrong result as far as user experience goes.

There needs to be a way (a flag would be great) to tell redis-rails that errors can be safely ignored.

**Comment by radar** [comment] 2015-04-15 04:25
Great! I can't believe it took that much to get a real example out of someone!

Please do investigate if there's not a better way than the above patch to fix this issue. If there's not, submit the patch as a PR and I will accept it.

**Comment by dsandber** [comment] 2015-04-15 04:27
At a minimum the patch needs to have a flag (or separate class) to enable both behaviors.  Apparently there's reasonable use cases for both the current behavior and the no-op behavior.

The current patch IIRC doesn't have this.

**Comment by dmitrypol** [comment] 2015-11-02 19:26
+1 for this fix.  I'd rather my site be slow that dead

**Comment by radar** [comment] 2015-11-02 21:18
@dmitrypol: have you tried the most recent release which has fixes for this sort of thing? Are you still having issues? If so, please detail them in a new issue.

**Comment by dsandber** [comment] 2015-11-03 05:47
I looked through the changelist but didn't see any changes that would affect this ticket.  Did I miss something?

**Comment by dmitrypol** [comment] 2015-11-03 14:21
Here are my repro steps for Rails 4.1.8:
Add redis and redis-rails gems to Gemfile.  
Add this to production.rb - config.cache_store = :redis_store, { host: server_name_here, port: 6379, db: 0, namespace: 'something',  expires_in: 1.minutes }
Start Rails in production
Verify that caching works.  
Shutdown Redis to simulate failure.  
Server response 500 and error in logs:
A, [2015-11-03T14:19:34.314926 #30154]   ANY -- : 2015-11-03 14:19:34 +0000 severity=FATAL, ActionView::Template::Error (getaddrinfo: Name or service not known):

**Comment by bjeanes** [comment] 2015-11-10 00:03
> It's not just for caching. It can be used as the session store too. 

@radar Agreed. The Redis connection in general shouldn't silently fail. *However*, a caching layer should in fact be transparent. An unavailable cache layer should be treated as a constant cache miss, not a critical error. Running Redis locally isn't an option for any non-trivial deployment (i.e. multiple servers) and network partitions **do happen**.

I take this to mean `ActiveSupport::Cache::RedisCache` or, to allow better configurability, a subclass/delegator thereof, has a circuit breaker which acts as a null store when the Redis instance is unavailable.

**Comment by radar** [comment] 2015-11-10 00:05
My apologies to all, I thought this issue had been fixed in a recent commit, particularly: https://github.com/redis-store/redis-activesupport/commit/f14e8cb3447facce512941c10143023fb0cca481.

I have also realised that I haven't released this commit as a proper gem version and so I'll attend to that now.

**Comment by radar** [comment] 2015-11-10 00:08
Released redis-activesupport 4.1.5 which has that commit I just mentioned.

----

@dmitrypol: could you please try bumping `redis-activesupport` to 4.1.5 and let me know if that issue still happens? I haven't tried myself (and don't have the time, because I should be doing Real Work(tm) instead) and so I'd really appreciate it if you could take some time out to try it for me.

Thanks!

**Comment by bjeanes** [comment] 2015-11-10 00:13
Nice @radar! Exercise for future contributors is probably to implement a robust circuitbreaker with a tight-ish timeout so that response times don't spike trying to connect to Redis. Caching layers should make things faster not slower, after all!

**Comment by dmitrypol** [comment] 2015-11-10 19:47
still got  severity=FATAL, ActionView::Template::Error (getaddrinfo: Name or service not known) even after upgrading to 4.1.5.  
The monkey patch by Paxa from Dec 18th, 2014 works fine.

**Comment by radar** [comment] 2015-11-16 02:24
FYI: I am looking for new maintainers for this and other repos.

http://ryanbigg.com/2015/11/open-source-work/

I will no longer work on this repo.

**Comment by tubbo** [comment] 2015-12-01 04:42
@dmitrypol If you'd like to refactor that monkey patch into a pull request, I'd be glad to look it over. Until then, I would say that throwing an exception when Redis is down is what we're going to stick with, because that is not only expected behavior from redis-rails, but also somewhat necessary if you are storing your session data in Redis as well as your cache. For a cache store, it might not make sense to kill the whole app just because its server is down, but what about sessions? Surely, you want people to be able to log in?

**Closed by tubbo** 2015-12-01 04:42 UTC

**Comment by zlx** [comment] 2016-08-24 04:14
Hi, @tubbo @radar 
Thanks for this great gem, it provide a complete solution for rails cache with redis. Like in previous comments, when redis not available or timeout sometimes, someone just want to ignore it , while others want to catch the error and do other things. 

I think if there is a option to detemine if raise exception or not will flexible enough and match mostly case. If you think it's good idea. I can provide a PR to fix it. 

Tell me if I missing something.

**Comment by joshco** [comment] 2021-06-21 01:14
I was running into _LOADING Redis is loading the dataset in memory_ when it was taking too long to read the append file.
I created this initializer
````
# config/initializers/redis_wait.rb
if ENV['REDIS_URL'].present?
  begin
    # Insert a Redis operation to retrieve data that your app depends on 
  rescue  Redis::CommandError => ex
    delay=ENV['REDIS_DELAY'].presence || 4
    puts "Redis is not yet ready.  waiting #{delay} seconds"
    sleep(delay)
    retry
  end
end
````
